[build-system]
build-backend = "poetry.core.masonry.api"
requires = ["poetry-core", "torch<2"]

[tool.coverage.run]
omit = ["cosypose", "megapose6d"]

[tool.isort]
profile = "black"

[tool.mypy]
exclude = ["cosypose", "megapose6d"]

[[tool.mypy.overrides]]
ignore_missing_imports = true
module = "pybullet"

[tool.poetry]
authors = ["Elliot Maître", "Yann Labbé"]
description = "Toolbox and trackers for object pose-estimation"
license = "BSD-2-Clause"
name = "happypose"
readme = "README.md"
version = "0.1.0"

[tool.poetry.dependencies]
addict = "^2.4.0"
bokeh = "^3.1.1"
bop-toolkit-lib = {path = "bop_toolkit"}
imageio = "^2.31.1"
joblib = "^1.2.0"
omegaconf = "^2.3.0"
# cosypose = {path = "happypose/pose_estimators/cosypose"} TODO: pep517
open3d = "^0.17.0"
opencv-contrib-python = "^4.7.0.72"
opencv-python = "^4.7.0.72"
panda3d = "=1.10.13"
pin = "^2.6.17"
pybullet = "^3.2.5"
pypng = "^0.20220715.0"
python = ">=3.8,<3.11"
pyyaml = "^6.0"
roma = "^1.3.2"
scikit-image = "^0.21.0"
scikit-learn = "^1.2.2"
scipy = "^1.10.1"
seaborn = "^0.12.2"
simplejson = "^3.19.1"
torch = {source = "cpu", version = "<2"}
torchvision = {source = "cpu", version = "<0.15.2"}
tqdm = "^4.65.0"
transforms3d = "^0.4.1"
trimesh = "^3.22.1"
webdataset = "^0.2.48"
wget = "^3.2"

[tool.poetry.group.dev]
optional = true

[tool.poetry.group.dev.dependencies]
black = "^23.3.0"
coverage = {extras = ["toml"], version = "^7.2.5"}
ipython = "^8.12.0"
pre-commit = "^3.2.1"
pybind11 = "^2.10.4"
ruff = "^0.0.260"

[tool.poetry.group.docs]
optional = true

[tool.poetry.group.docs.dependencies]
myst-parser = "^1.0.0"
sphinx = "^6.2.1"

[[tool.poetry.source]]
name = "cpu"
priority = "explicit"
url = "https://download.pytorch.org/whl/cpu"

[tool.poetry.urls]
changelog = "https://github.com/agimus-project/happypose/blob/main/CHANGELOG.md"

[tool.ruff]
extend-exclude = ["cosypose", "megapose6d"]
extend-ignore = ["D203", "D213"]
extend-select = ["A", "B", "C", "COM", "D", "EM", "EXE", "G", "N", "PTH", "RET", "RUF", "UP", "W", "YTT"]
target-version = "py38"

[tool.tomlsort]
all = true
